# we need superlevel permission in order to execute this build
sudo: required 
services:
  - docker

before_install:
  - docker build -t rasthanadocker/docker-react -f Dockerfile.dev . 

script:
  - docker run -e CI=true rasthanadocker/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "docker-react"
  env: "DockerReact-env"
  bucket_name: "elasticbeanstalk-ap-south-1-396143971329"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"
